### PR TITLE
open fake pr for checkmate

### PR DESCRIPTION
**Pull request by boldorider4**
https://anaconda.atlassian.net/browse/PKG-0000
- Done some work
- It worked really well

### CODE REVIEW

**Comment by JamesRobertsonGames** [comment]
Linting passed for PR {pr.title}

**Review by JamesRobertsonGames — APPROVED** [review]
Checkmate! All clear. :thumbs_up:

**Comment by JamesRobertsonGames** [comment]
Linting passed for PR {pr.title}

**Review by JamesRobertsonGames — APPROVED** [review]
Checkmate! All clear. :+1:

**Comment by JamesRobertsonGames** [comment]
Description does not meet requirements. Please include a JIRA ticket URL.

**Review by JamesRobertsonGames — CHANGES_REQUESTED** [review]
Looks like a stalemate. Needs review. :-1:.

**Comment by JamesRobertsonGames** [comment]
Description is empty. Please include a JIRA ticket URL and at least one bullet point.

**Comment by JamesRobertsonGames** [comment]
Linting passed for PR {pr.title}

**Review by JamesRobertsonGames — APPROVED** [review]
Checkmate! All clear. :+1:

**Comment by JamesRobertsonGames** [comment]
Linting passed for PR open fake pr for checkmate

**Review by JamesRobertsonGames — APPROVED** [review]
Checkmate! All clear. :+1:

**Comment by JamesRobertsonGames** [comment]
Linting passed for PR open fake pr for checkmate

**Review by JamesRobertsonGames — APPROVED** [review]
Checkmate! All clear. :+1:

**Comment by boldorider4** [comment]
I'm guessing this can be closed.

**Pull request closed without merging**
